### ISSUE TITLE
Multiparter test failed

### ISSUE THREAD

**Issue by JinnyYi** [beyondstorage/go-service-cos#30]
For [CompleteMultipartUpload in cos](https://intl.cloud.tencent.com/document/product/436/7742):
- If the numbers of the uploaded parts are not continuous, 400 `InvalidPart` will be returned when this API is called.
- If the part information entries in the request body are not sorted by number in ascending order, 400 `InvalidPartOrder` will be returned when this API is called.

Random part number in `CompletePart` test case leads to the failure of `multiparter` integration test.

**Comment by Xuanwo** [comment]
We need to update the tests and add comments for `CompletePart` in cos.

**Comment by Xuanwo** [comment]
Fixed.
