### ISSUE TITLE
Integration test fails when read with `Range: bytes=-xxx`

### ISSUE THREAD

**Issue by JinnyYi** [beyondstorage/go-service-cos#66]
## Expected Behavior

According to [COS API doc](https://cloud.tencent.com/document/product/436/7753), when `GetObject` with `Range` header:

```
例如 bytes=0-9，表示下载对象的开头10个字节的数据；bytes=5-9，表示下载对象的第6到第10个字节。此时返回 HTTP 状态码206（Partial Content）及 Content-Range 响应头部。
```

And also, `FormatRangeOptions()` was provided to format `Range` value in [cos-go-sdk](https://github.com/tencentyun/cos-go-sdk-v5/blob/master/helper.go#L304-L318):

```
func FormatRangeOptions(opt *RangeOptions) string {
	if opt == nil {
		return ""
	}
	if opt.HasStart && opt.HasEnd {
		return fmt.Sprintf("bytes=%v-%v", opt.Start, opt.End)
	}
	if opt.HasStart {
		return fmt.Sprintf("bytes=%v-", opt.Start)
	}
	if opt.HasEnd {
		return fmt.Sprintf("bytes=-%v", opt.End)
	}
	return ""
}
```

Based on the above, we envision that when `Range: bytes=-9` we should be able to download data from 0 to 9([0-9]).

## Current Behavior

- When setting `RangeOptions.End` as follows, we will get the read size check error.
  ```
  rangeOptions := &cos.RangeOptions{}
  if opt.HasSize {
		rangeOptions.HasEnd = true
		rangeOptions.End = rangeOptions.Start + opt.Size - 1
  }
  ```
- When setting `RangeOptions.End` as follows, we will get the read content check error.
  ```
  rangeOptions := &cos.RangeOptions{}
  if opt.HasSize {
		rangeOptions.HasEnd = true
		rangeOptions.End = opt.Size
  }
  ```

## Steps to Reproduce

Run integration test after modifying the code as above.

## Enviroment

github.com/tencentyun/cos-go-sdk-v5 v0.7.31

**Comment by JinnyYi** [comment]
> Based on the above, we envision that when `Range: bytes=-9` we should be able to download data from 0 to 9([0-9]).

Seems that `Range: bytes=-9` identifies the final 9 bytes, ref: https://datatracker.ietf.org/doc/html/rfc7233#section-2.1. I'll test and verify it later.

<blockquote><img src="https://www.ietf.org/lib/dt/7.38.0/ietf/images/ietf-icon-blue3.png" width="48" align="right"><div><strong><a href="https://datatracker.ietf.org/doc/html/rfc7233#section-2.1">rfc7233</a></strong></div><div>Hypertext Transfer Protocol (HTTP/1.1): Range Requests (RFC )</div></blockquote>

**Comment by JinnyYi** [comment]
`GetObject` with `Range: bytes=-5` will get the final 5 bytes. So if `Read` with only `size`, we have to set the `offset` to 0 actively.

![image](https://user-images.githubusercontent.com/82445294/137290050-fbb32f04-3f9c-4dbd-b038-6b2fef8a7a2c.png)

**Comment by Xuanwo** [comment]
Nice work!
